<a href="https://colab.research.google.com/github/Vasanth2703/Deep-Learning-Basics/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'
import tensorflow as tf
print(tf.__version__)

2.11.0


In [ ]:
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector=tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

NameError: ignored

In [ ]:
matrix=tf.constant([[10, 7], [7, 10]])
matrix

NameError: ignored

In [ ]:
import tensorflow as tf
matrix=tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix=tf.constant([[10., 7.],
                            [3., 2.],
                            [8., 7.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  7.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
vector=tf.constant([10, 10])
vector.ndim

1

In [ ]:
tensor=tf.constant([[[1, 2, 3],
                    [4, 5, 6]],
                    [[7, 8, 9],
                    [8, 9, 0]],
                    [[1, 2, 3],
                     [3, 4, 5]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [8, 9, 0]],

       [[1, 2, 3],
        [3, 4, 5]]], dtype=int32)>

In [ ]:
tensor.ndim

In [ ]:
import tensorflow as tf
*Scalar:a single number
*Vector: a numebr with directioin(e.g. wind speed and direction)
*Matrix: a 2-dimensional array of numbers
*Tensors:an n-dimensional array of numbers(where n can be any number, a 0-dimensional tensor is a vector)

In [ ]:
import tensorflow as tf
changeable_tensor=tf.Variable([10, 7])
unchangeable_tensor=tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [ ]:
#creating random tensors
#Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
#create two random (but the same) tensors
random_1=tf.random.Generator.from_seed(42) #set seeed for reproducibilty
random_1=random_1.normal(shape=(3, 2))
random_1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
import tensorflow as tf
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3, 2))
random_2=tf.random.Generator.from_seed(42)
random2=random_2.normal(shape=(3, 2))


#are they equal


ValueError: ignored

In [ ]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2

In [ ]:
random_1 == random_2

ValueError: ignored

In [ ]:
#shuffle a tensor (valuable for when you want to shuffle your fataso the inherent)
not_shuffled=tf.constant([[10, 7],
                          [3, 4],
                          [2, 5]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#shuffle our non shuffled tensor
tf.random.shuffle(not_shuffled)

NameError: ignored

In [ ]:
import tensorflow as tf

not_shuffled=tf.constant([[10, 7],
                          [3, 4],
                          [2, 5]])
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#other ways to make tensors

In [ ]:
tf.zeros(shape=(3, 4))


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#You can also turn NumPy arrays into tensors
#The main difference between NumPy and Tensorflow is that tensors can be run on a GPU
#(computing)

In [ ]:
import numpy as np
numpy_A=np.arange(1, 25, dtype=np.int32)# create a Numpy array between 1 and 25
numpy_A



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A=tf.constant(numpy_A, shape=(2, 3, 4))
B=tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
2*3*4


24

In [ ]:
print("Hello World")

Hello World


In [ ]:
###Getting information from tensors

In [ ]:
import tensorflow as tf



In [ ]:
#When dealing with tensors you want to probably want to be aware of the following attributes:
#Shape
#Rank
#Axis or dimension
#size

In [ ]:
#Create a rank 4 tensor(4 dimension)
rank_4_tensor=tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
 rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5


120

In [ ]:
#Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions(rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total numner of elements in our tensor:", tf.size(rank_4_tensor))

Datatype of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total numner of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
print("Total numner of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Total numner of elements in our tensor: 120


In [ ]:
#We can use .numpy() to simplify the appearance of output like above


In [ ]:
#Indexing Tensors
#Tensors can be indexed just like Python lists.


In [ ]:
some_list=[1, 2, 3, 4]
some_list[:2]

[1, 2]

In [ ]:
#Get the first two elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor(2 dimension)
rank_2_tensor1=tf.zeros(shape=[1, 3])
rank_2_tensor1

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>

In [ ]:
rank_2_tensor=tf.constant([[10, 7],
                           [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
rank_3_tensor=rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)#-1 means expand the final axis
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)#expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
###Manipulate tensors(tensor operations)

In [ ]:
#Basic operations
#+, -, *, /

In [ ]:
#You can add values to a tensor using the addition operator
tensor=tf.constant([[10, 7], [3, 4]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#original tensor is unchanged

In [ ]:
#Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#Subtraction if you want
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#We can use the tensorflow built in funcion
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#matrix addition
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Matrix Multiplication
#in machine learning, matrix multiplication is one of the most common tensor operations.
#There arw two rules our tensors need to fulfil if we're going to matrix multiply them:
#1.The inner dimensions must match
#2.The resulting matrix has the same shape of the inner dimensions
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Matrix multiplication with python operator "@"
tensor@tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
#Create a tensor (3, 2) tensor
x=tf.constant([[1, 2],
               [3, 4],
               [5, 6]])
y=tf.constant([[7, 8],
               [9, 10],
               [11, 12]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#Try to matrix multiply tensors of same shape
tf.matmul(x, y)

In [ ]:
import tensorflow as tf
x=tf.constant([[1, 2],
               [3, 4],
               [5, 6]])
y=tf.constant([[7, 8],
               [9, 10],
               [11, 12]])


In [ ]:
#Let's change the shape of y
tf.reshape(y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
#Try to multiply x by reshaped y
x@tf.reshape(y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(x, tf.reshape(y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(x, shape=(2, 3)), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.reshape(x, shape=(2, 3)).shape, y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
#transpose and reshape are different in the positions of element but are same in reshaping
tf.transpose(x), tf.reshape(x, shape=(2, 3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
import tensorflow as tf


In [ ]:
a=tf.constant([1.3, 2.4])
a.dtype

tf.float32

In [ ]:
b=tf.constant([1, 2])
b.dtype

tf.int32

In [ ]:
#Change from float32 to float16(reduced precision)
a=tf.cast(a, dtype=tf.float16)
a, a.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.3, 2.4], dtype=float16)>,
 tf.float16)

In [ ]:
#Change from int32 to float16
e=tf.cast(b, dtype=tf.float16)
e, e.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>,
 tf.float16)

In [ ]:
#Aggregating tensors
tf.__version__

'2.11.0'

In [ ]:
#Aggregating tensors=condensing them from multiple values down to a smaller amount of values.


In [ ]:
#Get the absolute values
d=tf.constant([-7, -10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
#Get the absolute values
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
import tensorflow as tf

In [ ]:
#Let's go throught the following forms of aggregation:
#Get the minimum
#Get the maximum
#Get the mean of a tensor
#Get the sum of a tensorm

In [ ]:
#Create a random tensor with values between 0 and 100 and of size 50
import numpy as np
E=tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 1,  4, 73, 35, 14, 88, 78, 15, 74, 78, 56, 42, 14, 53, 82, 43, 54,
       22, 25, 25,  5, 32, 65, 52, 83, 60, 96,  1, 93, 73, 30, 84, 71, 89,
       69, 65, 58, 40, 41, 96, 27, 40, 43, 27, 83, 39, 54, 83, 67, 11])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
#Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
#Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
#Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2553>

In [ ]:
#Exercise With what we've just learned, find the variance and the standard deviation of our E tensor

In [ ]:
#To find the variance of our tensor, we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=766>

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.680613>

In [ ]:
#To use the above function the tensor should have real or complex


In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=766.2163>

AttributeError: ignored

In [ ]:
#Find the positional maximum and minimum


In [ ]:
#Create a new tensor for finding the positional minimum and maximum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
np.argmax(F)

42

In [ ]:
#Index on our largest value position
F[tf.argmax(F)].numpy()

0.9671384

In [ ]:
#Check for equality
F[tf.argmax(F)]==tf.reduce_max(F)


<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
F[tf.argmin(F)]==tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
#Find the minimum using the positional minimum
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
#Squeezing a tensor(removing all single dimensions)


In [ ]:
#Create a tensor to get started
G=tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

One-Hot Encoding

In [ ]:
import tensorflow as tf
#Create a list of indices
some_list=[0, 1, 2, 3]#could be red, green, blue, purple
#One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify the custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo", off_value="oy")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo', b'oy', b'oy', b'oy'],
       [b'oy', b'yo', b'oy', b'oy'],
       [b'oy', b'oy', b'yo', b'oy'],
       [b'oy', b'oy', b'oy', b'yo']], dtype=object)>

Squaring, log, square root

In [ ]:
#Create a new tensor
H=tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Find the square root(will error, method requires non-int type)
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

Tensors and NumPy
Tensorflow interacts beautifully with NumPy array

In [ ]:
#Create a tensor directly from a NumPy array
import numpy as np

J=tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#The default types of each are different
numpy_J=tf.constant(np.array([3., 7., 10.]))
tensor_J=tf.constant([3., 7., 10.])
#Check the dataypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [ ]:
import tensorflow as tf
